{
 "title": "ETH Beacon Chain Node",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_job", "query": "beacon node" },
   { "name": "validator_job", "query": "validator" }
  ]
 },
 "panels": [
  {
   "title": "Warn alert: The process just restarted",
   "type": "graph",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds)/3600",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Alert: More than 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Beacon Chain",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Mem usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 14, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Peers connected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 9 },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"error\"}[1h]) > 0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "ALERTS",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 } },
  {
   "title": "Number of slot behind",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot"
    }
   ]
  },
  {
   "title": "Node process started",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 14, "y": 13 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$node_job\"})/3600"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Alert: More than 50 errors in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]))",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]))",
     "legendFormat": "warnings"
    }
   ]
  }
 ]
}