{
 "title": "ETH staking dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "node_job", "query": "beacon node" },
   { "name": "validator_job", "query": "validator" }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "text",
   "description": "To delete this panel: left click on the title, then chose remove",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "content": "\n## Presentation\n---------------\nWelcome to my dashboard!\n\nIf you face any issue to understand a panel or to know what to do, make sure to read the small note on the corner top left of the panel if there is one!\n\n\n\n### Bug!\n---------------\n\nIf you find a bug, please report it to me on discord, Ocaa/grums. I'm foundable on the prysm discord then dm me directly. I'll try to give a fix and update the dashboard on the gist!\nThanks for all the reports\n\n\n\n\n-------------\nAfter reading it, you can now delete me. And don't forget to save the dashboard after deleting me! (button on the upper right) :)\n\nEnjoy\n\n\n\n"
  },
  {
   "title": "VALIDATOR",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hourly earning (ETH)",
   "type": "singlestat",
   "description": "The hourly earning will be available once your first validator activated is at least 1 hour old, or you started Prometheus at least 1 hour ago.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32"
    }
   ]
  },
  {
   "title": "Daily earning (ETH)",
   "type": "singlestat",
   "description": "The daily earning will be available once your first validator activated is at least 1 day old, or you started Prometheus at least 1 day ago.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1d) - count(validator_balance > 16)*32 + count(validator_balance offset 1d > 0)*32"
    }
   ]
  },
  {
   "title": "Weekly earning (ETH)",
   "type": "singlestat",
   "description": "The weekly earning will be available once your first validator activated is at least 7 days old, or you started Prometheus at least 7 days ago.",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1w) - count(validator_balance > 16)*32 + count(validator_balance offset 1w > 0)*32"
    }
   ]
  },
  {
   "title": "Monthly earning (ETH)",
   "type": "singlestat",
   "description": "The monthly earning will be available once your first validator activated is at least 30 days old, or you started Prometheus at least 30 days ago.\n\nAlso make sure you run prometheus with the flag --storage.tsdb.retention.time=31d",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 30d) - count(validator_balance > 16)*32 + count(validator_balance offset 30d > 0)*32"
    }
   ]
  },
  {
   "title": "Total earning  (ETH)",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(validator_balance)-count(validator_balance > 16 and validator_statuses == 3)*32"
    }
   ]
  },
  {
   "title": "Validator process started",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 12 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$validator_job\"})/3600"
    }
   ]
  },
  {
   "title": "Total balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    { "expr": "sum(validator_balance > 16)", "legendFormat": "Total balance" }
   ]
  },
  {
   "title": "Validator balance",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_balance > 16, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Validator main info",
   "type": "table",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_balance), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by(pubkey) (validator_statuses), \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "Validator vote summary",
   "type": "table",
   "description": "This panel will count only the votes done since your validator process started",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "label_replace(max by(pubkey) (validator_successful_attestations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_failed_attestations)  , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey)(validator_successful_aggregations)    , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_aggregations) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_successful_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    },
    {
     "expr": "label_replace(max by (pubkey) (validator_failed_proposals) , \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")"
    }
   ]
  },
  {
   "title": "BOTH",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "NODE",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 11, "x": 8, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "NODE" }
   ]
  },
  {
   "title": "ALERTS",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Hardware usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "decbytes", "label": "mem usage" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "memory {{job}}" },
    {
     "expr": "(process_cpu_seconds_total - process_cpu_seconds_total offset 15s) > 0*100/15/go_maxprocs",
     "legendFormat": "CPU {{job}}"
    }
   ]
  },
  {
   "title": "Balance validators status and participation rate",
   "type": "graph",
   "description": "This graph is made for trading purpose mostly.\nSupposing that if a lot of validators are exiting, price is gonna dump.\n\nAlso this can prevent to exit while exiting queue is too long, same for depositing while pending queue is too long.\n\n",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "ETH" }
   ],
   "targets": [
    {
     "expr": "validators_total_balance{state=\"Active\"} / 10e8",
     "legendFormat": "Active"
    },
    {
     "expr": "validators_total_balance{state=\"Pending\"} / 10e8",
     "legendFormat": "Pending"
    },
    {
     "expr": "validators_total_balance{state=\"Exiting\"} / 10e8",
     "legendFormat": "Exiting"
    },
    {
     "expr": "total_voted_target_balances/total_eligible_balances*100",
     "legendFormat": "Participation rate"
    }
   ]
  },
  {
   "title": "Node process started",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 25 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds{job=\"$node_job\"})/3600"
    }
   ]
  },
  { "title": "All alerts", "type": "alertlist", "gridPos": { "h": 10, "w": 5, "x": 19, "y": 25 } },
  {
   "title": "Number of slot behind",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 27 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot"
    }
   ]
  },
  {
   "title": "Peers connected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 16, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "p2p_peer_count{state=\"Connected\"}"
    }
   ]
  },
  {
   "title": "Hourly log type counter",
   "type": "bargauge",
   "description": "This panel won't have consistant values during the first hour of the node started process",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"error\"}[1h]) > 0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"$node_job\", level=\"warning\"}[1h]) > 0)",
     "legendFormat": "warning"
    }
   ]
  },
  {
   "title": "Warn: The process just restarted",
   "type": "graph",
   "description": "This alert is useful only for people who has automatic restart of the process after crash. \nThis can be made for example by using the prysm.bat file on windows with \"set PRYSM_AUTORESTART=true&\", or with docker with \"--restart always\"",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(time()-process_start_time_seconds)/3600",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Alert: More than 50 slots behind",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "beacon_clock_time_slot-beacon_head_slot",
     "legendFormat": "node slots behind"
    }
   ]
  },
  {
   "title": "Alert: Process down",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Alert: Hourly earning <= 0",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(validator_balance) - sum(validator_balance offset 1h) - count(validator_balance > 16)*32 + count(validator_balance offset 1h > 0)*32",
     "legendFormat": "validators earning on 1h"
    }
   ]
  },
  {
   "title": "Alert: More than 50 errors in 1h",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"error\"}[1h]))",
     "legendFormat": "errors"
    },
    {
     "expr": "sum(delta(log_entries_total{job=\"beacon node\", level=\"warning\"}[1h]))",
     "legendFormat": "warnings"
    }
   ]
  },
  {
   "title": "Alert: Validator has been slashed",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(validator_statuses, \"pubkey\", \"$1\", \"pubkey\", \"(.{10}).*\")",
     "legendFormat": "{{pubkey}}"
    }
   ]
  },
  {
   "title": "Alert: Participation rate < 66%",
   "type": "graph",
   "gridPos": { "h": 1, "w": 5, "x": 19, "y": 41 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "total_voted_target_balances/total_eligible_balances*100"
    }
   ]
  }
 ]
}